"""Baseline migration

Revision ID: 62baca9db874
Revises: 
Create Date: 2026-09-29 10:52:10.986270

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62baca9db874'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    tables = inspector.get_table_names()

    if 'audit_logs' not in tables:
        op.create_table('audit_logs',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('claim_id', sa.String(), nullable=True),
        sa.Column('action', sa.String(), nullable=False),
        sa.Column('actor', sa.String(), nullable=False),
        sa.Column('details', sa.JSON(), nullable=False),
        sa.Column('previous_hash', sa.String(), nullable=True),
        sa.Column('entry_hash', sa.String(), nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
        sa.PrimaryKeyConstraint('id')
        )
    if 'claims' not in tables:
        op.create_table('claims',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('patient_name', sa.String(), nullable=False),
        sa.Column('patient_email', sa.String(), nullable=True),
        sa.Column('patient_phone', sa.String(), nullable=True),
        sa.Column('portal_token', sa.String(), nullable=True),
        sa.Column('policy_number', sa.String(), nullable=True),
        sa.Column('claim_number', sa.String(), nullable=True),
        sa.Column('status', sa.String(), nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
        sa.PrimaryKeyConstraint('id')
        )
    if 'analysis_runs' not in tables:
        op.create_table('analysis_runs',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('claim_id', sa.String(), nullable=False),
        sa.Column('status', sa.String(), nullable=False),
        sa.Column('result_data', sa.JSON(), nullable=True),
        sa.Column('forensics_data', sa.JSON(), nullable=True),
        sa.Column('overall_status', sa.String(), nullable=True),
        sa.Column('total_monetary_impact', sa.Float(), nullable=False),
        sa.Column('started_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
        sa.Column('completed_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
    if 'documents' not in tables:
        op.create_table('documents',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('claim_id', sa.String(), nullable=False),
        sa.Column('document_type', sa.String(), nullable=False),
        sa.Column('filename', sa.String(), nullable=False),
        sa.Column('original_filename', sa.String(), nullable=True),
        sa.Column('file_path', sa.String(), nullable=False),
        sa.Column('content_type', sa.String(), nullable=False),
        sa.Column('file_size_bytes', sa.Integer(), nullable=False),
        sa.Column('document_hash', sa.String(length=64), nullable=True),
        sa.Column('extracted_data', sa.JSON(), nullable=True),
        sa.Column('extraction_confidence', sa.Float(), nullable=True),
        sa.Column('extraction_method', sa.String(), nullable=True),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
        sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_documents_document_hash'), 'documents', ['document_hash'], unique=False)
    
    if 'rule_verdicts' not in tables:
        op.create_table('rule_verdicts',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('analysis_run_id', sa.String(), nullable=False),
        sa.Column('rule_name', sa.String(), nullable=False),
        sa.Column('rule_description', sa.String(), nullable=True),
        sa.Column('status', sa.String(), nullable=False),
        sa.Column('confidence', sa.Float(), nullable=False),
        sa.Column('finding', sa.Text(), nullable=False),
        sa.Column('insurer_calculation', sa.Float(), nullable=True),
        sa.Column('correct_calculation', sa.Float(), nullable=True),
        sa.Column('monetary_impact', sa.Float(), nullable=True),
        sa.Column('regulatory_citation', sa.String(), nullable=True),
        sa.Column('appeal_recommendation', sa.Text(), nullable=True),
        sa.Column('evidence_data', sa.JSON(), nullable=True),
        sa.Column('actual_claim_fact', sa.Text(), nullable=True),
        sa.Column('applicable_policy_rule', sa.Text(), nullable=True),
        sa.Column('insurer_applied_action', sa.Text(), nullable=True),
        sa.Column('expected_action', sa.Text(), nullable=True),
        sa.Column('difference', sa.Float(), nullable=True),
        sa.Column('evidence', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
        sa.ForeignKeyConstraint(['analysis_run_id'], ['analysis_runs.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
    
    if 'evidence_ledger_records' not in tables:
        op.create_table('evidence_ledger_records',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('claim_id', sa.String(), nullable=False),
        sa.Column('analysis_run_id', sa.String(), nullable=True),
        sa.Column('rule_verdict_id', sa.String(), nullable=True),
        sa.Column('document_id', sa.String(), nullable=True),
        sa.Column('document_hash', sa.String(length=64), nullable=False),
        sa.Column('page_number', sa.Integer(), nullable=False),
        sa.Column('bounding_box', sa.JSON(), nullable=True),
        sa.Column('section', sa.String(), nullable=True),
        sa.Column('source_text', sa.Text(), nullable=False),
        sa.Column('extracted_value', sa.JSON(), nullable=True),
        sa.Column('normalized_value', sa.JSON(), nullable=True),
        sa.Column('rule_id', sa.String(), nullable=True),
        sa.Column('formula', sa.String(), nullable=True),
        sa.Column('calculation_inputs', sa.JSON(), nullable=True),
        sa.Column('final_output', sa.JSON(), nullable=True),
        sa.Column('confidence', sa.Float(), nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
        sa.ForeignKeyConstraint(['analysis_run_id'], ['analysis_runs.id'], ),
        sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ),
        sa.ForeignKeyConstraint(['rule_verdict_id'], ['rule_verdicts.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_evidence_ledger_records_analysis_run_id'), 'evidence_ledger_records', ['analysis_run_id'], unique=False)
        op.create_index(op.f('ix_evidence_ledger_records_claim_id'), 'evidence_ledger_records', ['claim_id'], unique=False)
        op.create_index(op.f('ix_evidence_ledger_records_document_hash'), 'evidence_ledger_records', ['document_hash'], unique=False)
        op.create_index(op.f('ix_evidence_ledger_records_document_id'), 'evidence_ledger_records', ['document_id'], unique=False)
        op.create_index(op.f('ix_evidence_ledger_records_rule_id'), 'evidence_ledger_records', ['rule_id'], unique=False)
        op.create_index(op.f('ix_evidence_ledger_records_rule_verdict_id'), 'evidence_ledger_records', ['rule_verdict_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_evidence_ledger_records_rule_verdict_id'), table_name='evidence_ledger_records')
    op.drop_index(op.f('ix_evidence_ledger_records_rule_id'), table_name='evidence_ledger_records')
    op.drop_index(op.f('ix_evidence_ledger_records_document_id'), table_name='evidence_ledger_records')
    op.drop_index(op.f('ix_evidence_ledger_records_document_hash'), table_name='evidence_ledger_records')
    op.drop_index(op.f('ix_evidence_ledger_records_claim_id'), table_name='evidence_ledger_records')
    op.drop_index(op.f('ix_evidence_ledger_records_analysis_run_id'), table_name='evidence_ledger_records')
    op.drop_table('evidence_ledger_records')
    op.drop_table('rule_verdicts')
    op.drop_index(op.f('ix_documents_document_hash'), table_name='documents')
    op.drop_table('documents')
    op.drop_table('analysis_runs')
    op.drop_table('claims')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
